name: CI/CD
on: 
  push:
    branches: [ temporary-azure-connection ]
  pull_request:
    branches: [ temporary-azure-connection ]

jobs:      
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: ${{ secrets.DOCKER_IMAGE }}
          tags: Micflix-Streaming-Platform
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}